
services:
  db:
    image: mysql:latest
    #container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/karan/go/src/github.com/karanrn/go-rest-api/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${root_password}